# Prerequisites

In [1]:
import sys

sys.path.append("..")

In [2]:
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np
from tqdm.notebook import tqdm

from dataset import HWSetMasks

C:\Users\runes\.conda\envs\context\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:41: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.
  warnings.warn(


# Estimate channelwise mean and std

In [3]:
trainset = HWSetMasks("../data", "train")

In [4]:
channels = []
channels_mask = []
for i in tqdm(range(len(trainset))):
    im, _, mask = trainset[i]
    im, mask = np.array(im), np.array(mask)
    channels.append(im.reshape(-1, 3))
    channels_mask.append(im[mask != 0])

  0%|          | 0/932 [00:00<?, ?it/s]

In [5]:
channels = np.vstack(channels)
channels_mask = np.vstack(channels_mask)

In [6]:
channels_mean = channels.mean(0) / 255
channels_std = channels.std(0) / 255
channels_mask_mean = channels_mask.mean(0) / 255
channels_mask_std = channels_mask.std(0) / 255

In [7]:
channels, channels_mask = None, None

In [9]:
channels_mean.round(3), channels_std.round(3), channels_mask_mean.round(3), channels_mask_std.round(3)

(array([0.453, 0.444, 0.405]),
 array([0.258, 0.256, 0.27 ]),
 array([0.495, 0.467, 0.435]),
 array([0.25 , 0.247, 0.246]))